# Generated by Django 5.1.2 on 2024-10-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_contactform_alter_flan_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="ContactForm",
        ),
    ]
