# Generated by Django 5.1.2 on 2024-10-23 00:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_remove_flan_flan_uuid_remove_flan_slug_flan_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flan",
            name="flan_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
