# Generated by Django 5.1.2 on 2024-10-23 00:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_flan_flan_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flan",
            name="flan_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
