# Generated by Django 5.1.2 on 2024-10-23 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_alter_flan_flan_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="flan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentarios",
                to="web.flan",
            ),
        ),
    ]
